### ISSUE TITLE
How to export preview to file?

### ISSUE THREAD

**Issue by sinhpn92** [luthfipun/Minecraft3DSkinRenderer#1]
Hi @luthfipun,
This repository is very useful with me. It's will be more awesome if have the function that's help to export the 3d previewer to image file.

Thank you so much.

**Comment by luthfipun** [comment]
Thank's @sinhpn92  for your feedback, maybe next time will be added. i'm busy right now.
alternatively you can take screenshot the view on the background like [this](https://stackoverflow.com/questions/2661536/how-to-programmatically-take-a-screenshot-on-android), and save to the storages or galleries

**Comment by sinhpn92** [comment]
@luthfipun Thank you so much. I have done to save the image. Now I want to create some skin poses. Could you help me for that?
